### ISSUE TITLE
Confusing language for IDE users

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/sql-intro-and-installation#8]
References to `brew`/`homebrew` are confusing for PC users. It is not clear they should be using the IDE.  @PeterBell

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
